# docker-compose.yml

version: '3.8'

services:
  react-app:
    build:
      context: ./house-payments-tracker
      dockerfile: Dockerfile
    container_name: react-app-dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules #  Prevents the node_modules directory from being overridden by the mounted directory.
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - payments-net
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-splitter-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - payments-net
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - payments-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_SITE_BASEURL=/
      - ME_CONFIG_SITE_PORT=8081
    networks:
      - payments-net

volumes:
  mongodb_data:

networks:
  payments-net:
