# docker-compose.override.yml

version: '3.8'

services:
  react-app:
    build:
      context: ./house-payments-tracker
      dockerfile: Dockerfile.dev
    container_name: react-app-client
    ports:
      - '3000:3000' # Application port
    volumes:
      - ./house-payments-tracker:/app #  Mounts the current directory to /app inside the container, enabling live updates.
      - /app/node_modules #  Prevents the node_modules directory from being overridden by the mounted directory.
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - expense-net
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - '8080:8080' # Application port
      - '9229:9229' # Debugger port
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - expense-net
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
