# docker-compose.prod.yml

version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: expense-splitter-client
    ports:
      - '8080:80'
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - expense-net
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-splitter-backend
    ports:
      - '8080:30808000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - expense-net
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - expense-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_SITE_BASEURL=/
      - ME_CONFIG_SITE_PORT=8081
    networks:
      - expense-net

volumes:
  mongodb_data:

networks:
  expense-net:
